"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var readlineSync = require("readline-sync");
var vuelta1 = readlineSync.questionInt("Ingrese el tiempo de la 1er vuelta: ");
var vuelta2 = readlineSync.questionInt("Ingrese el tiempo de la 2da vuelta: ");
var vuelta3 = readlineSync.questionInt("Ingrese el tiempo de la 3er vuelta: ");
var vuelta4 = readlineSync.questionInt("Ingrese el tiempo de la 4ta vuelta: ");
var tiempoTotal = vuelta1 + vuelta2 + vuelta3 + vuelta4;
var tiempoPromedio = tiempoTotal / 4;
console.log("El tiempo total fue de " + tiempoTotal);
console.log("El tiempo promedio por vuelta fue de: " + tiempoPromedio);
